apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configmap
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
data:
  SPRING_DATA_SOURCE_URL: jdbc:mysql://{{.Release.Name}}-mysql:3306/{{.Values.mysql.auth.database}}
  REDIS_DATABASE: "{{.Values.redis.database}}"
  REDIS_HOST: {{.Release.Name}}-redis-master
  REDIS_PORT: "6379"
  KAFKA_CONSUMER_ID: "1"
  IMICONNECT_SMS_SEND_API_URL: "{{.Values.imiConnect.url}}"
  ELASTICSEARCH_CLUSTER_NODE: {{.Release.Name}}-elasticsearch-coordinating-hl:9200
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
