apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secrets
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_USERNAME: {{.Values.mysql.auth.username | b64enc}}
  MYSQL_PASSWORD: {{.Values.mysql.auth.password | b64enc}}
  IMICONNECT_API_KEY: {{.Values.imiConnect.apiKey | b64enc}}
