CREATE TABLE blacklist_mobile_numbers_v1 (
     id INT PRIMARY KEY AUTO_INCREMENT,
     phone_number VARCHAR(20) NOT NULL,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);